[package]
name = "sim7000"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-time = "0.12"
heapless = "0.7"
embedded-hal = "0.2"
log = "0.4"