[env.probe]
protocol = "Swd"
speed = 4000

[env.flashing]
enabled = true
halt_afterwards = false
restore_unwritten_bytes = false
do_chip_erase = false

[env.reset]
enabled = true
halt_afterwards = false

[env.general]
chip = "NRF52840_XXAA"
chip_descriptions = []
#   "OFF", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"
log_level = "WARN"
connect_under_reset = false

# Whether RTT or GDB or none only.

[env.rtt]
enabled = true
# Channel associations to be displayed. All shown when not selected. { String, Defmt, BinaryLE }
channels = [{ up = 0, name = "defmt_r", format = "Defmt" }]
# { up = 0, name = "defmt_name", format = "Defmt" }
timeout = 3000
show_timestamps = true
log_enabled = true
log_path = "../../debuglog"

[env.gdb]
enabled = false
gdb_connection_string = "127.0.0.1:1337"
