[package]
name = "sim7000-async"
version = "0.1.0"
authors = ["Zoey Riordan <zoey@dos.cafe>"]
description = "Drivers for the SIM7000 series of chips"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/technocreatives/sim7000"

edition = "2021"

[dependencies]
embedded-hal-async = { version = "0.0.1", git = "https://github.com/embassy-rs/embedded-hal", branch = "embassy2"}
embedded-hal = { version = "1.0.0-alpha.8" }
embassy = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy", branch = "master", features = [ "nightly", "time" ]}
heapless = "0.7"
futures-util = { version = "0.3", default-features = false }
log = "0.4"
critical-section = "0.2.7"